#!/bin/bash
#SBATCH --job-name=shsup16
#SBATCH --output=16.csv
#SBATCH --nodes=3
#SBATCH --nodelist=gojo,bocchi,megumi

files=("tests/10k" "tests/5k" "tests/2.5k" "tests/1.25k")

touch 16.csv
echo "tam,threads,total,sequencial,paralelo" > 16.csv 

for file in "${files[@]}"; do
    for i in {1..5}; do
      srun -n 3 --mpi=pmix ./shsup "$file" 
  done
done 

