#!/bin/bash
#SBATCH --job-name=shsup4
#SBATCH --output=4.csv
#SBATCH --nodes=1
#SBATCH --nodelist=megumi

files=("tests/10k" "tests/5k" "tests/2.5k" "tests/1.25k")

touch 4.csv
echo "tam,threads,total,sequencial,paralelo" > 4.csv 

for file in "${files[@]}"; do
    for i in {1..5}; do
      srun -n 1 --mpi=pmix ./shsup "$file" 
  done
done 

